name: flutter_webrtc_demo
description: A new Flutter application.
version: 1.2.0

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.22.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  flutter_webrtc: ^0.9.3
  shared_preferences: ^2.0.7
  http: ^0.13.3
  path_provider: ^2.0.2
  pretty_dio_logger: ^1.1.1
  get_it: ^7.2.0
  json_serializable: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.2
  retrofit_generator: ^4.0.3

flutter:
  uses-material-design: true
